/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import { BalloonAbi, DexAbi } from "~~/utils/Constants";

const deployedContracts = {
  devnet: {
    Balloons: {
      address:
        "0x6e2019cc7b4bba6683f527a3e136ceb1e1bc6e177aeda26caf8e9b88a2d1615",
      abi: BalloonAbi,
      classHash:
        "0xd495652b125d2e15ebdfbb1c9586241d2a386186d36d80b38a9a2d38936a1",
    },
    Dex: {
      address:
        "0x7fcbb20648038a16c9cf691f5c216f6c618a05216a6e70c91f2abe120d12649",
      abi: DexAbi,
      classHash:
        "0x1f5440cf160dc29c45dd8473adbc1e731d2468cdeb4a66a0e65fea201301fe0",
    },
  },
} as const;

export default deployedContracts;
