/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import { BalloonAbi, DexAbi } from "~~/utils/Constants";

const deployedContracts = {
  devnet: {
    Balloons: {
      address:
        "0x7bdf22823ca1fb2719a9fe2fef9d382e50b07902be0b595e71e576a845d6af6",
      abi: BalloonAbi,
      classHash:
        "0x2ff6bdd942d4465a86cdcd5edf6a384345302ffdac14842e48e26ffd78ec7ff",
    },
    Dex: {
      address:
        "0x6732388eca3c2ae0260a2b4812a058ec774e7b008049fd005639299069dd4a1",
      abi: DexAbi,
      classHash:
        "0x1f5440cf160dc29c45dd8473adbc1e731d2468cdeb4a66a0e65fea201301fe0",
    },
  },
} as const;

export default deployedContracts;
