/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import {
  devnetStrkClassHash,
  universalStrkAddress,
  sepoliaMainnetStrkClassHash,
  strkAbi,
  DexAbi
} from "../utils/Constants";

const preDeployedContracts = {
  devnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: devnetStrkClassHash,
    },
  },
  sepolia: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
    Dex: {
      address: "0x50c230b59db2646e7741c845cd890ecb5766bcd82993e2051719eec4779c9bf",
      abi: DexAbi,
    },

  },
  mainnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
  },
} as const;

export default preDeployedContracts;
