/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import {
  devnetStrkClassHash,
  universalStrkAddress,
  sepoliaMainnetStrkClassHash,
  strkAbi,
  DexAbi,
  BalloonAbi,
  sepoliaDexAddress,
  sepoliaDexClassHash,
  sepoliaBalloonAddress,
  sepoliaBalloonClassHash
} from "../utils/Constants";

const preDeployedContracts = {
  devnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: devnetStrkClassHash,
    },
  },
  sepolia: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
    Dex: {
      address: sepoliaDexAddress,
      abi: DexAbi,
      classHash: sepoliaDexClassHash,
    },
    Balloons: {
      address: sepoliaBalloonAddress,
      abi: BalloonAbi,
      classHash: sepoliaBalloonClassHash,
    },

  },
  mainnet: {
    Strk: {
      address: universalStrkAddress,
      abi: strkAbi,
      classHash: sepoliaMainnetStrkClassHash,
    },
  },
} as const;

export default preDeployedContracts;
